### ISSUE TITLE
What is the hardware used to test this code ?

### ISSUE THREAD

**Issue by X-Ryl669** [ElectronicCats/ElectronicCats-PN7150#13]
I've found your store, and I'm wondering what is the hardware used to test this PN7150 code?
Can I buy it ?
Is it [this one](https://www.nxp.com/products/rfid-nfc/nfc-hf/nfc-readers/development-kits-for-pn7150-plugn-play-nfc-controller:OM5578) ?

**Comment by sabas1080** [comment]
Hi @X-Ryl669 

We don't have our own hardware yet, soon we will have hardware in our store, while you can use the hardware that you mention, it is compatible
