### ISSUE TITLE
I2C in ESP32

### ISSUE THREAD

**Issue by hkarthik97** [ElectronicCats/ElectronicCats-PN7150#16]
I tried to connect ESP32 and PN7150 plug and play device. I connected in I2C. The serial monitor shows Setup Ok. But when I scan the card nothing happens. Which microcontroller did you use?

**Comment by sabas1080** [comment]
Hi @hkarthik97 

This library is not ready to work in ESP32 yet, apparently there is not enough buffer for the responses of the PN7150, but welcome your pullrequest, check wire library

https://github.com/ElectronicCats/ElectronicCats-PN7150/blob/master/src/Electroniccats_PN7150.h#L23-L32

this library has been tested on SAMD21, but should work on SMT32, Teensy and similary boards

**Comment by sabas1080** [comment]
Hi @hkarthik97 this library work for you in ESP32?

**Comment by hkarthik97** [comment]
Yes it works for me in esp32

**Comment by HighCodeh** [comment]
> Sim, funciona para mim no esp32

Hello, I wanted to know how you implemented it for use on the es32? I'm trying to use the pn7150 with the esp32 but I'm not succeeding!!

**Comment by Eric286** [comment]
Hello @HighCodeh 

Please verify with an I2C scanner that the module is recognized to eliminate the possibility that this is the problem.

I also recommend trying with another card, if you have it available, to see if the error is directly due to the ESP32 or not.

Kind Regards!

**Comment by HighCodeh** [comment]
Could you tell me which pins are used in the respective pins of the pn7150 module?
