### ISSUE TITLE
Is it possible to read the data stored in the card

### ISSUE THREAD

**Issue by hkarthik97** [ElectronicCats/ElectronicCats-PN7150#17]
I am storing some text in my card. I am not able to read the data will this library read the data stored in the card?
Thanks in advance

**Comment by salmg** [comment]
What type of card? What type of technology? Which hardware did you use to write it? Which example are you using to read it? Do you have some code?.....

Difficult to guess all those variables.

**Comment by hkarthik97** [comment]
I  want to transfer text from my phone NFC via NDEF.I am using PN7150. I am used both Detect tags and Readblock mifare classic example

**Comment by hkarthik97** [comment]
Any update on this?

**Comment by hkarthik97** [comment]
Please help .. 
Will don/ndef library help?

**Comment by sabas1080** [comment]
@hkarthik97 NDEF it is a feature we are working on

**Comment by hkarthik97** [comment]
> @hkarthik97 NDEF it is a feature we are working on

When is it expected to be released?

**Comment by salmg** [comment]
Soon

**Comment by hkarthik97** [comment]
When will you release the update for P2P?

**Comment by sabas1080** [comment]
@hkarthik97 P2P work in beta, yo can clone this repo, but NDEF no yet, we are working

**Comment by sabas1080** [comment]
#25
