### ISSUE TITLE
To read NFC message(Using NFC support Phone) through NFC reader

### ISSUE THREAD

**Issue by ram-prasanth-9394** [ElectronicCats/ElectronicCats-PN7150#18]
I want to read NFC messages (from inbuild NFC support phone) through NFC reader. 
Can you help me to get through this ?

Thank You. 
Regards Ram.

**Comment by salmg** [comment]
The NDEF feature is not added yet, we are working on that part of the code

**Comment by sabas1080** [comment]
#25
