### ISSUE TITLE
Is there a way to use this library in a nonblocking way?

### ISSUE THREAD

**Issue by schmidty1913** [ElectronicCats/ElectronicCats-PN7150#22]
nfc.WaitForDiscoveryNotification(&RfInterface) is a blocking function, is there a way to have it non blocking?

**Comment by salmg** [comment]
If you explain what you want to do, we can see if there is other way to do it. That function specifically is designed to be like that because is always looking for cards

**Comment by schmidty1913** [comment]
I am looking to have the library wait for a card but also be able to loop.

I am looking to receive serial commands and also blink an LED.

**Comment by salmg** [comment]
what we can do is to add a parameter to the function to make it more flexible about timeout; i will add this change to the next modification, thanks

**Comment by schmidty1913** [comment]
I was thinking it would be better to have a function that checks for the IRQ pin. Call that function and it returns false if the IRQ is not set and returns card data if the IRQ is set

**Comment by salmg** [comment]
yes please, add the functionality, and we can review it

**Comment by sabas1080** [comment]
@salmg @schmidty1913 

I have pullrequest with interrupt and IRQ #24

**Comment by sabas1080** [comment]
Now in #46
