### ISSUE TITLE
I2C clock frequency

### ISSUE THREAD

**Issue by Josephh2021** [ElectronicCats/ElectronicCats-PN7150#27]
Hi,

I am using Arduino Mega 2560 to control PN7150 NFC Reader using I2C.  I am measuring 100KHZ for I2C clock.  I have been trying to change it using Wire.setClock(400000) command but it is not changing the frequency.  Please let me know what I am doing wrong.  Thanks.

Joseph

**Comment by sabas1080** [comment]
Hi @Josephh2021 

try to make the change before or after the wire.begin
https://github.com/ElectronicCats/ElectronicCats-PN7150/blob/master/src/Electroniccats_PN7150.cpp#L62

**Comment by Josephh2021** [comment]
Thanks for the response.
