### ISSUE TITLE
ISO 14443-3A tag detection error(?)

### ISSUE THREAD

**Issue by wolfmanus** [ElectronicCats/ElectronicCats-PN7150#31]
Additional result of an [another](https://github.com/ElectronicCats/ElectronicCats-PN7150/issues/29#issuecomment-1055523842) thread at the request of @Arthulisher :
### not recognized TAG:
by my S21 phone, NFC Tools Pro app:

> Tag type: ISO 14443-3A, Innovision R&T Jewel - Topaz 512
Technologies available: NfcA, Ndef
Serial number: XX:XX:XX:XX
ATQA: 0x0C00
SAK: 0x00
Header ROM: 0x124C
Memory information: 512 bytes
Data format: NFC Forum Type 1

by MIKROE PN7150 mudul, v1.5.1 ISO14443-3A_read_block sample

> 15:26:50.543 -> Read ISO14443-3A(T2T) data block 5 with PN7150
15:26:50.543 -> Initializing...
15:26:50.615 -> Waiting for an ISO14443-3A Card ...
15:26:57.216 -> - Found a card, but it is not ISO14443-3A(T2T)!
15:26:58.816 -> CARD REMOVED!
15:26:58.816 -> Re-initializing...

by MIKROE PN7150 mudul, v1.5.1 DetectTags sample

> 15:31:27.743 -> Detect NFC tags with PN7150
15:31:27.743 -> Initializing...
15:31:27.803 -> Waiting for an Card ...
15:31:30.964 -> - POLL MODE: Remote activated tag type: 1
15:31:30.964 -> SENS_RES = 0x00 0x0C
15:31:30.964 -> NFCID =
15:31:32.604 -> CARD REMOVED!
15:31:32.604 -> Re-initializing...

**Comment by jazhe** [comment]
Hello @wolfmanus!
We apologize for the delay, and we thank you so much for your patience.
Unfortunately, we do not have an ISO14443-3A card to replicate your issue, we are sorry for the inconvenience caused.
However, feel free to get back to us if you have any further queries.
