### ISSUE TITLE
NDEF record reading?

### ISSUE THREAD

**Issue by howlingwolven** [ElectronicCats/ElectronicCats-PN7150#48]
The documentation and examples are unclear; is there a method that'll return a whole NDEF record stored on a tag? If so, how do I implement it?

**Comment by Eric286** [comment]
Hello @howlingwolven!

I am very sorry for the inconveniences that the documentation and examples could cause you by not being clear.

At the moment we do not have NDEF implemented and in fact we have a pull request where you can see how to start implementing it.

https://github.com/ElectronicCats/ElectronicCats-PN7150/pull/25/files

Here I leave the direct link so you can see this and if you want to start using it, however there are still things to do, we are working on it.
Also, if you wish and it is not urgent, you can wait a while for all this to be ready.

Best Regard!
Support Team!

**Comment by Eric286** [comment]
Hello @howlingwolven!

I will close the issue.

Please do not hesitate to reach out again if you have any further questions or concerns in the future. 

We are always here to help.

Best regards,

**Comment by sabas1080** [comment]
#25

**Comment by sabas1080** [comment]
now available
