### ISSUE TITLE
Is Card emulation possible?

### ISSUE THREAD

**Issue by LeSuedois** [ElectronicCats/ElectronicCats-PN7150#49]
Hello,
I have some PN7150 Boards laying around and I want to make a little Arduino project where visitors of my install can scan this board and get the link to the projects page.
Is this possible with this library?
I saw stuff in the library that let me think it's possible..
If it's possible but not yet implemented I think I will do the code and PR. 

Thank you,
Simon

**Comment by jazhe** [comment]
Hello Simon!
It is possible to emulate a card but to share a URL you must do it with NDEF (which is not implemented yet).
Your contributions are so welcome! 

Best,
Electronic Cats Support Team

**Comment by sabas1080** [comment]
#25
